### ISSUE TITLE
Referencias a bloques de notas (`^bloque`)

### ISSUE THREAD

**Issue by 4k4m1m3** [comunidad-hacking-etico-espanol/obsidian-vault-template#1]
_**Describe claramente la pregunta o confusión que estás experimentando.**_
Al momento de realizar la exportación de la bóveda y colocarlo en modo de edición, en algunas partes observo algunos textos, tipo:

- ^objetivo
- ^recursos
- ^bandera
- ^etc

**Contexto adicional**
Esto me ocurre solo en modo de edición, en modo lectura no aparece el texto, es como que si no se estuviera funcionando algo correctamente.

**Comment by 15Galan** [comment]
Lo que mencionas son **referencias a bloques**[^1] de una nota.

Igual que puedes mencionar una nota usando `[[Nota]]`, también puedes mencionar específicamente partes del contenido de la nota usando `[[Nota#^bloque]]`.

Además, como es una referencia, quiere decir que si su valor se actualiza (es decir, el texto al que apunta se modifica), también se verá reflejado en los sitios donde se use dicha referencia.

**Ejemplo**

Si quieres escribir una nota sobre las diferencias entre una VPN y un Proxy, y ya tienes una nota que habla sobre lo que es una VPN y lo define, podrías referenciar ese texto en específico usando `^definicion`.

Ahora, podrías usar `![[VPN#^definicion]]` en la nota sobre las diferencias para referenciar y mostrar el contenido de la nota VPN, pero sola y exclusivamente el texto de su definición.

[^1]: Obsidian Help - [Link to a block in a note](https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note)

**Comment by ghost** [comment]
Entiendo perfectamente, muchas gracias por tu ayuda @15Galan 
En vista que no es error, solo ignorancia de capa 8, procedo a cerrar el issues.
