### ISSUE TITLE
Writeups de Una al mes

### ISSUE THREAD

**Issue by 4k4m1m3** [comunidad-hacking-etico-espanol/obsidian-vault-template#2]
Estoy chequeando el directorio de plantillas para los Writeups, y observo que una de las plataformas es: **Una al mes**, sin embargo a diferencia del resto, esta al momento de querer crear un writeups de esta plataforma no se me muestra en las opciones.

**Contexto adicional**
[Foto evidencia](https://gcdnb.pbrd.co/images/Xp4rUJu6JHdo.png)

**Comment by 15Galan** [comment]
Se resolvió el problema.

![Menu](https://github.com/comunidad-hacking-etico-espanol/obsidian-vault-template/assets/26381506/1ba45516-8fcb-4cea-a664-ffcf7f293f31)
